In [124]:
import numpy as np

# numpy version
print(np.__version__)

# create np array
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr)

# double the elements of array
arr *=2
print(arr)

# dimension of array
print(arr.ndim)

# multi-dimensional array
md_arr = np.array([[1,2,3], [4,5,6]])
print(md_arr.ndim)
print(md_arr.shape) # (layers, rows, columns)

n_arr = np.array([
  [['a', 'b', 'c'], ['d', 'e', 'f']],
  [['g', 'h', 'i'], ['j', 'k', 'l']],
  [['m', 'n', 'o'], ['p', 'q', 'r']],
  [['s', 't', 'u'], ['v', 'w', 'x']]
])
print(n_arr.shape)
print(n_arr[2,0,1]) # n
print(n_arr[2][0][1]) # n

# slicing
new_arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(new_arr[0:2])
print(new_arr[::-1])
print(new_arr[::2])

# scalar arithmetic
a_arr = np.array([1,2,3])
print(a_arr+4) # [5,6,7]
print(a_arr-2) # [-1 0 1]
print(a_arr*2) # [2 4 6]
print(a_arr/2) # [0.5 1 1.5]
print(a_arr**2) # [1 4 9]

# vectorized math functions
print(np.sqrt(a_arr))
print(np.round(a_arr))
print(np.pi)
print(a_arr + new_arr)
print(a_arr - new_arr)
print(a_arr * new_arr)

# comparison operators
scores = np.array([55, 66, 97, 82, 45, 65, 57, 98, 99, 92, 44, 88, 16, 14, 12, 2])
print(scores > 60)

# broadcasting
b_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

c_array = np.array([10, 20, 30])

print(b_array + c_array)
print(b_array.shape)
print(c_array.shape)

# aggregate functions
ag_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(ag_array.sum())
print(ag_array.mean())
print(ag_array.std())
print(ag_array.var())
print(ag_array.min())
print(ag_array.max())
print(ag_array.argmin()) # pos of min val
print(ag_array.argmax()) # # pos of max val
print(np.sum(ag_array, axis=0))
print(np.sum(ag_array, axis=(1))
)

# filtering
ages = np.array([[12, 15, 16, 17, 18, 25, 35, 36], [38, 39, 40, 45, 46, 47, 49, 50]])
print(ages[(ages >= 18) & (ages <= 40)])
print(np.where(ages>=18, "minor", "adult")) # if age>=18 show adult else show minor

# random numbers
rng = np.random.default_rng()
print(rng.integers(1, 50, 5)) # low | high | size
print(np.random.uniform(-1, 1, (3,2)))

rng.shuffle(ages)
print(ages)

sel_age = rng.choice(scores, 2)
print(sel_age)

2.5.2
<class 'numpy.ndarray'>
[1 2 3 4 5]
[ 2  4  6  8 10]
1
2
(2, 3)
(4, 2, 3)
n
n
[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[1 2 3]
 [7 8 9]]
[5 6 7]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]
[1.         1.41421356 1.73205081]
[1 2 3]
3.141592653589793
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 0  0  0]
 [-3 -3 -3]
 [-6 -6 -6]]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[False  True  True  True False  True False  True  True  True False  True
 False False False False]
[[11 22 33]
 [14 25 36]
 [17 28 39]]
(3, 3)
(3,)
55
5.5
2.8722813232690143
8.25
1
10
0
9
[ 7  9 11 13 15]
[15 40]
[18 25 35 36 38 39 40]
[['adult' 'adult' 'adult' 'adult' 'minor' 'minor' 'minor' 'minor']
 ['minor' 'minor' 'minor' 'minor' 'minor' 'minor' 'minor' 'minor']]
[44 13  3  7 19]
[[-0.10447787  0.16913223]
 [ 0.95218517  0.95014995]
 [-0.08323635  0.1366227 ]]
[[38 39 40 45 46 47 49 50]
 [12 15 16 17 18 25 35 36]]
[45 99]
